"""barber_service table

Revision ID: 116986c690fb
Revises: 0c86c677ae0a
Create Date: 2026-09-09 19:13:56.828029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116986c690fb'
down_revision: Union[str, None] = '0c86c677ae0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barber_services',
    sa.Column('shop_barber_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_barber_id'], ['shop_barbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_barber_id', 'service_id', name='uq_barber_service')
    )
    op.create_index('ix_barber_services_barber_service', 'barber_services', ['shop_barber_id', 'service_id'], unique=False)
    op.create_index(op.f('ix_barber_services_id'), 'barber_services', ['id'], unique=False)
    op.create_index(op.f('ix_barber_services_service_id'), 'barber_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_barber_services_shop_barber_id'), 'barber_services', ['shop_barber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barber_services_shop_barber_id'), table_name='barber_services')
    op.drop_index(op.f('ix_barber_services_service_id'), table_name='barber_services')
    op.drop_index(op.f('ix_barber_services_id'), table_name='barber_services')
    op.drop_index('ix_barber_services_barber_service', table_name='barber_services')
    op.drop_table('barber_services')
    # ### end Alembic commands ###
