"""create barber wooking hours table

Revision ID: 3f56a73da38c
Revises: 7a9ef4594fe9
Create Date: 2026-09-11 19:58:16.559412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f56a73da38c'
down_revision: Union[str, None] = '7a9ef4594fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barber_working_hours',
    sa.Column('shop_barber_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_barber_id'], ['shop_barbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_barber_working_hours_barber_day', 'barber_working_hours', ['shop_barber_id', 'day_of_week'], unique=True)
    op.create_index(op.f('ix_barber_working_hours_id'), 'barber_working_hours', ['id'], unique=False)
    op.create_index(op.f('ix_barber_working_hours_shop_barber_id'), 'barber_working_hours', ['shop_barber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barber_working_hours_shop_barber_id'), table_name='barber_working_hours')
    op.drop_index(op.f('ix_barber_working_hours_id'), table_name='barber_working_hours')
    op.drop_index('ix_barber_working_hours_barber_day', table_name='barber_working_hours')
    op.drop_table('barber_working_hours')
    # ### end Alembic commands ###
