"""add_image_to_shop_barbers

Revision ID: 788eb772282c
Revises: 116986c690fb
Create Date: 2026-09-11 17:53:01.851411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '788eb772282c'
down_revision: Union[str, None] = '116986c690fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_barbers', sa.Column('image', sa.String(length=500), nullable=True))
    op.alter_column('shop_barbers', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last successful login timestamp',
               existing_nullable=True)
    op.drop_index('ix_shop_barbers_barber_id', table_name='shop_barbers')
    op.drop_constraint('uq_shop_barber', 'shop_barbers', type_='unique')
    op.create_unique_constraint('uq_shop_barber', 'shop_barbers', ['shop_id', 'display_name'])
    op.drop_constraint('shop_barbers_barber_id_fkey', 'shop_barbers', type_='foreignkey')
    op.drop_column('shop_barbers', 'barber_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_barbers', sa.Column('barber_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('shop_barbers_barber_id_fkey', 'shop_barbers', 'users', ['barber_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_shop_barber', 'shop_barbers', type_='unique')
    op.create_unique_constraint('uq_shop_barber', 'shop_barbers', ['shop_id', 'barber_id'])
    op.create_index('ix_shop_barbers_barber_id', 'shop_barbers', ['barber_id'], unique=False)
    op.alter_column('shop_barbers', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last successful login timestamp',
               existing_nullable=True)
    op.drop_column('shop_barbers', 'image')
    # ### end Alembic commands ###
