"""add_unique_index_to_business

Revision ID: 7a9ef4594fe9
Revises: 3f24d511c484
Create Date: 2026-09-11 19:28:04.512970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9ef4594fe9'
down_revision: Union[str, None] = '3f24d511c484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
