"""shop barber

Revision ID: b663ca19a806
Revises: 14fa0b4da24c
Create Date: 2026-09-07 16:42:22.512417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b663ca19a806'
down_revision: Union[str, None] = '14fa0b4da24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_barbers',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('barber_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful login timestamp'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'barber_id', name='uq_shop_barber')
    )
    op.create_index(op.f('ix_shop_barbers_barber_id'), 'shop_barbers', ['barber_id'], unique=False)
    op.create_index(op.f('ix_shop_barbers_display_name'), 'shop_barbers', ['display_name'], unique=False)
    op.create_index(op.f('ix_shop_barbers_id'), 'shop_barbers', ['id'], unique=False)
    op.create_index('ix_shop_barbers_shop_active', 'shop_barbers', ['shop_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_shop_barbers_shop_id'), 'shop_barbers', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_barbers_shop_id'), table_name='shop_barbers')
    op.drop_index('ix_shop_barbers_shop_active', table_name='shop_barbers')
    op.drop_index(op.f('ix_shop_barbers_id'), table_name='shop_barbers')
    op.drop_index(op.f('ix_shop_barbers_display_name'), table_name='shop_barbers')
    op.drop_index(op.f('ix_shop_barbers_barber_id'), table_name='shop_barbers')
    op.drop_table('shop_barbers')
    # ### end Alembic commands ###
